### ISSUE TITLE
Unable to run a sample

### ISSUE THREAD

**Issue by Leon99** [coherentsolutionsinc/aspnetcore-service-fabric-hosting#98]
I'm get the message below when pressing F5 in VS 2019 on \samples\configuring-service\Code.sln:

---------------------------
Microsoft Visual Studio
---------------------------
The active solution configuration is not configured to build or deploy the Service Fabric Application project.  This can happen if the solution configuration is not configured to build/deploy the x64 platform which this project requires.  An attempt will be made to debug launch the project.  The application on the cluster, if it exists, may not be up-to-date with the source code since the project was not built and deployed. Do you want to continue?
---------------------------
Yes   No   
---------------------------

Any ideas what that means and why it appears? SF v7.1.428.9590

**Comment by OlegKarasik** [comment]
Hi @Leon99 
Thanks for the question. I will check this and get back to you.

**Comment by Leon99** [comment]
I managed to fix the initial error by checking Build/Deploy boxes for App project in the Solution Configuration. I'd gladly submit a PR with the fixed .sln, but the app still doesn't start:
![image](https://user-images.githubusercontent.com/6840381/90455477-8214ad00-e139-11ea-842b-b9963c064eb6.png)

**Comment by OlegKarasik** [comment]
Hi @Leon99,

Can you recheck whether you are using the correct solutions configuration i.e. **Debug/x64** or **Release/x64**? I am asking because sample solution already has 'checked' Deploy box for App project.

![image](https://user-images.githubusercontent.com/36962980/90623407-16a50b00-e21f-11ea-81e2-4c4d2b3b9f8f.png)

**Comment by Leon99** [comment]
OK I figured I had a wrong active solution platform selected (although normally Any CPU on csproj-s work just fine with SF). However, even with the x64 platform it still won't run:

```
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[39236] dotnet.exe' has exited with code -2147450730 (0x80008096).
```

**Comment by OlegKarasik** [comment]
@Leon99, can you install .NET Core 2.2? The error you mention can be triggered by absence of the required .NET Core runtime.

The current project is configured as `netcoreapp2.2` (you can check this in Service.csproj). 

```xml
<PropertyGroup>
  <TargetFramework>netcoreapp2.2</TargetFramework>
  <Platforms>AnyCPU;x64</Platforms>
</PropertyGroup>
```

**Comment by Leon99** [comment]
Installing 2.2 helped, thanks a lot.
It would be nice to change it to an LTS version though, since 2.2 is out of support now (even VS Installer shows that...)

**Comment by OlegKarasik** [comment]
I am glad you've solved the issues. Also, as you've suggested I have updated the samples to reference LTS (3.1) .NET Core release and latest (at this moment 7.1) version of SF nugets (PR #100)
